name: apod
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  envied: ^0.5.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  http: ^1.2.1
  youtube_player_flutter: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  envied_generator: ^0.5.3
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  image_path: "assets/launcher_icon/android/play_store_512.png"
  android: true # can specify file name here e.g. "ic_launcher"
  adaptive_icon_background: "assets/launcher_icon/android/res/mipmap-xxxhdpi/ic_launcher_background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/launcher_icon/android/res/mipmap-xxxhdpi/ic_launcher_foreground.png" # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "assets/launcher_icon/android/res/mipmap-xxxhdpi/ic_launcher_monochrome.png" # only available for Android 13 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  ios: false
